<?php
/**
 * Default options for homepage landing cards and the two long-scroll pages.
 *
 * @package LifeRuss
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Landing-related default options (merged into the main tree).
 *
 * @return array
 */
function liferuss_landing_default_options() {
	return array(
		'home_landings_enabled'  => '1',
		'home_landings_eyebrow'  => 'مسیرهای همکاری',
		'home_landings_title'    => 'باربری و تجارت ایران و روسیه',
		'home_landings_subtitle' => 'علاوه بر مشاوره تحصیل، ارسال بار و تأمین کالا بین ایران و روسیه را هم شفاف و قابل پیگیری همراهی می‌کنیم.',
		'home_landings'          => array(
			array(
				'enabled' => '1',
				'title'   => 'باربری، کارگو و ارسال',
				'text'    => 'ارسال محموله‌های تجاری، نمونه کالا، وسایل شخصی و مدارک دانشجویی بین ایران و روسیه.',
				'cta'     => 'درخواست ارسال بار',
				'link'    => '/freight/',
				'icon'    => 'cargo',
			),
			array(
				'enabled' => '1',
				'title'   => 'تجارت، تأمین و سورسینگ',
				'text'    => 'خرید از روسیه، صادرات محصولات ایران و تأمین اختصاصی کالا برای بازرگانان.',
				'cta'     => 'درخواست تأمین کالا',
				'link'    => '/trade/',
				'icon'    => 'handshake',
			),
		),

		'freight_hero_enabled'   => '1',
		'freight_hero_eyebrow'   => 'Iran ↔ Russia · Cargo & Delivery',
		'freight_hero_headline'  => 'باربری، کارگو و ارسال بین ایران و روسیه',
		'freight_hero_accent'    => 'ایران و روسیه',
		'freight_hero_lead'      => 'لایف روس مسیر ارسال محموله‌های تجاری، نمونه کالا، وسایل شخصی و مدارک دانشجویی را از ثبت درخواست تا تحویل در مقصد همراهی می‌کند.',
		'freight_hero_cta_text'  => 'ثبت درخواست ارسال',
		'freight_hero_cta_link'  => '#consultation',
		'freight_hero_image_id'  => 0,
		'freight_hero_image'     => 'st-basil.jpg',
		'freight_trust'          => array(
			array( 'title' => 'پشتیبانی تمام‌مسیر', 'text' => 'از ثبت تا تحویل در مقصد', 'icon' => 'chat' ),
			array( 'title' => 'هماهنگی کامل', 'text' => 'ایران و روسیه در یک تیم', 'icon' => 'shield' ),
			array( 'title' => 'شبکه لجستیکی', 'text' => 'کارگو، زمینی و هوایی', 'icon' => 'globe' ),
			array( 'title' => 'ارسال ایمن', 'text' => 'پیگیری و اعلام وضعیت', 'icon' => 'bolt' ),
		),

		'freight_services_enabled' => '1',
		'freight_services'         => array(
			array( 'enabled' => '1', 'title' => 'کارگو و باربری تخصصی', 'text' => 'حمل محموله‌های تجاری، بارهای حجیم و خریدهای FCL / LCL با مسیرهای هوایی، زمینی و ترکیبی.', 'icon' => 'cargo', 'image' => 'universities/bauman.jpg', 'image_id' => 0 ),
			array( 'enabled' => '1', 'title' => 'ارسال نمونه کالا برای بازرگانان', 'text' => 'ارسال نمونه‌های تجاری و کاتالوگ برای عرضه، نمایشگاه و مذاکره در بازار روسیه و ایران.', 'icon' => 'box', 'image' => 'universities/hse.jpg', 'image_id' => 0 ),
			array( 'enabled' => '1', 'title' => 'حمل بار و وسایل شخصی', 'text' => 'ارسال لوازم زندگی، اثاثیه و وسایل شخصی دانشجویان و مهاجران با بسته‌بندی مطمئن.', 'icon' => 'suitcase', 'image' => 'universities/spbu.jpg', 'image_id' => 0 ),
			array( 'enabled' => '1', 'title' => 'ارسال مدارک و بسته‌های دانشجویی', 'text' => 'ارسال امن مدارک دانشگاهی، دیپلم، ریزنمرات و بسته‌های سبک بین ایران و روسیه.', 'icon' => 'docs', 'image' => 'universities/sechenov.jpg', 'image_id' => 0 ),
		),

		'freight_process_enabled'  => '1',
		'freight_process_title'    => 'مراحل همکاری',
		'freight_process_subtitle' => 'از ثبت درخواست تا تحویل در مقصد، در کنار شما هستیم.',
		'freight_process'          => array(
			array( 'num' => '۱', 'title' => 'ثبت درخواست', 'text' => 'تکمیل فرم و ارسال اطلاعات اولیه محموله.' ),
			array( 'num' => '۲', 'title' => 'بررسی نوع بار', 'text' => 'بررسی حجم، وزن و محدودیت‌های گمرکی.' ),
			array( 'num' => '۳', 'title' => 'اعلام روش و هزینه', 'text' => 'پیشنهاد مسیر، زمان و برآورد هزینه.' ),
			array( 'num' => '۴', 'title' => 'تحویل و ارسال', 'text' => 'بسته‌بندی، تحویل و پیگیری حمل.' ),
			array( 'num' => '۵', 'title' => 'تحویل در مقصد', 'text' => 'هماهنگی تحویل ایمن در شهر مقصد.' ),
		),

		'freight_form_enabled'        => '1',
		'freight_form_title'          => 'فرم درخواست ارسال بار',
		'freight_form_intro'          => 'جزئیات محموله را بفرستید تا مسیر، زمان و برآورد هزینه را اعلام کنیم.',
		'freight_form_banner_title'   => 'اتصال مطمئن ایران به روسیه',
		'freight_form_banner_text'    => 'More than cargo — a stronger tomorrow',
		'freight_form_banner_image'   => 'consult-student.jpg',
		'freight_form_banner_image_id'=> 0,
		'freight_form_name_label'     => 'نام و نام خانوادگی',
		'freight_form_name_ph'        => 'مثلاً سارا احمدی',
		'freight_form_phone_label'    => 'شماره تماس / واتساپ',
		'freight_form_phone_ph'       => '۰۹۱۲xxxxxxx',
		'freight_form_origin_label'   => 'مبدأ (شهر / کشور)',
		'freight_form_origin_ph'      => 'مثلاً تهران',
		'freight_form_dest_label'     => 'مقصد (شهر / کشور)',
		'freight_form_dest_ph'        => 'مثلاً مسکو',
		'freight_form_type_label'     => 'نوع کالا / محموله',
		'freight_form_types'          => array(
			array( 'label' => 'انتخاب کنید', 'value' => '' ),
			array( 'label' => 'بار تجاری', 'value' => 'commercial' ),
			array( 'label' => 'نمونه کالا', 'value' => 'sample' ),
			array( 'label' => 'وسایل شخصی', 'value' => 'personal' ),
			array( 'label' => 'مدارک دانشجویی', 'value' => 'docs' ),
			array( 'label' => 'سایر', 'value' => 'other' ),
		),
		'freight_form_weight_label'   => 'وزن تقریبی (کیلوگرم)',
		'freight_form_weight_ph'      => 'مثلاً ۵۰',
		'freight_form_dims_label'     => 'ابعاد تقریبی',
		'freight_form_dims_ph'        => 'طول × عرض × ارتفاع',
		'freight_form_packages_label' => 'تعداد بسته‌ها',
		'freight_form_packages_ph'    => 'مثلاً ۳',
		'freight_form_value_label'    => 'ارزش تقریبی کالا (دلار)',
		'freight_form_value_ph'       => 'مثلاً ۱۰۰۰',
		'freight_form_notes_label'    => 'توضیحات تکمیلی',
		'freight_form_notes_ph'       => 'جزئیات بیشتر در مورد نوع بار، زمان ارسال یا محدودیت‌ها',
		'freight_form_file_label'     => 'آپلود عکس یا فایل مربوط به بار',
		'freight_form_file_note'      => 'فرمت مجاز: JPG، PNG، PDF — حداکثر ۱۰ مگابایت',
		'freight_form_submit'         => 'ارسال درخواست',
		'freight_form_note'           => 'اطلاعات فقط برای هماهنگی ارسال استفاده می‌شود.',
		'freight_form_success'        => 'درخواست ارسال ثبت شد. مشاوران لایف روس به‌زودی با شما تماس می‌گیرند.',

		'freight_items_enabled'  => '1',
		'freight_items_title'    => 'موارد معمول ارسال',
		'freight_items_subtitle' => 'نمونه‌هایی از کالاهایی که معمولاً بین ایران و روسیه ارسال می‌شوند.',
		'freight_items'          => array(
			array( 'title' => 'مدارک', 'image' => 'universities/msu.jpg', 'image_id' => 0 ),
			array( 'title' => 'وسایل شخصی', 'image' => 'universities/spbu.jpg', 'image_id' => 0 ),
			array( 'title' => 'نمونه کالا', 'image' => 'universities/hse.jpg', 'image_id' => 0 ),
			array( 'title' => 'بسته دانشجویی', 'image' => 'universities/sechenov.jpg', 'image_id' => 0 ),
			array( 'title' => 'لوازم آرایشی', 'image' => 'universities/rudn.jpg', 'image_id' => 0 ),
			array( 'title' => 'قطعات و کالا', 'image' => 'universities/bauman.jpg', 'image_id' => 0 ),
			array( 'title' => 'بار تجاری', 'image' => 'st-basil.jpg', 'image_id' => 0 ),
		),
		'freight_items_notice'   => 'اگر کالای موردنظر شما در این فهرست نیست یا احتمال محدودیت و ممنوعیت دارد، پیش از ارسال با لایف روس هماهنگ کنید. برخی کالاها نیاز به مجوز گمرکی دارند.',

		'freight_cta_enabled'    => '1',
		'freight_cta_title'      => 'آماده ارسال محموله هستید؟',
		'freight_cta_text'       => 'مسیر، زمان و برآورد هزینه را شفاف اعلام می‌کنیم.',
		'freight_cta1_text'      => 'درخواست ارسال بار',
		'freight_cta1_link'      => '#consultation',
		'freight_cta2_text'      => 'مشاوره کارگو لایف روس',
		'freight_cta2_link'      => '/contact/',
		'freight_seo_title'      => 'باربری و ارسال ایران و روسیه | لایف روس',
		'freight_seo_description'=> 'ارسال کارگو، نمونه کالا، وسایل شخصی و مدارک دانشجویی بین ایران و روسیه با لایف روس.',

		'trade_hero_enabled'     => '1',
		'trade_hero_eyebrow'     => 'Iran ↔ Russia · Trade & Sourcing',
		'trade_hero_headline'    => 'تجارت، تأمین و سورسینگ کالا بین ایران و روسیه',
		'trade_hero_accent'      => 'ایران و روسیه',
		'trade_hero_lead'        => 'لایف روس مسیر تجارت بین‌المللی، خرید از روسیه، صادرات محصولات ایران و سورسینگ اختصاصی را برای بازرگانان شفاف و قابل پیگیری می‌کند.',
		'trade_hero_cta_text'    => 'ثبت درخواست تأمین',
		'trade_hero_cta_link'    => '#consultation',
		'trade_hero_image_id'    => 0,
		'trade_hero_image'       => 'st-basil.jpg',
		'trade_trust'            => array(
			array( 'title' => 'تأمین مطمئن', 'text' => 'شبکه تأمین‌کنندگان بررسی‌شده', 'icon' => 'shield' ),
			array( 'title' => 'راهکار اختصاصی', 'text' => 'خرید، صادرات و سورسینگ', 'icon' => 'handshake' ),
			array( 'title' => 'شبکه بین‌المللی', 'text' => 'ایران، روسیه و مسیر سوم', 'icon' => 'globe' ),
			array( 'title' => 'رشد پایدار تجارت', 'text' => 'از نمونه تا قرارداد', 'icon' => 'bolt' ),
		),

		'trade_services_enabled' => '1',
		'trade_services'         => array(
			array( 'enabled' => '1', 'title' => 'سورسینگ اختصاصی برای شرکتها و بازرگانان', 'text' => 'یافتن تأمین‌کننده مناسب برای حجم خرید، مقصد و مشخصات فنی کالای شما.', 'icon' => 'search', 'image' => 'universities/hse.jpg', 'image_id' => 0 ),
			array( 'enabled' => '1', 'title' => 'تأمین بین‌المللی کالا', 'text' => 'داروینی، ادویه، جواهر، غلات، خشکبار و کالاهای صنعتی از شبکه تأمین منطقه‌ای.', 'icon' => 'globe', 'image' => 'universities/msu.jpg', 'image_id' => 0 ),
			array( 'enabled' => '1', 'title' => 'خرید کالا از روسیه', 'text' => 'لوازم آرایشی و بهداشتی، مواد اولیه و کالاهای اختصاصی بازار روسیه.', 'icon' => 'cart', 'image' => 'universities/rudn.jpg', 'image_id' => 0 ),
			array( 'enabled' => '1', 'title' => 'صادرات و تأمین محصولات ایران', 'text' => 'پسته، خرما، مواد غذایی و محصولات قابل صادرات از ایران به مقصد روسیه.', 'icon' => 'box', 'image' => 'universities/sechenov.jpg', 'image_id' => 0 ),
		),

		'trade_process_enabled'  => '1',
		'trade_process_title'    => 'مراحل همکاری',
		'trade_process_subtitle' => 'مسیر ساده تا تأمین کالا',
		'trade_process'          => array(
			array( 'num' => '۱', 'title' => 'ثبت درخواست', 'text' => 'ارسال اطلاعات اولیه کالا و بازار هدف.' ),
			array( 'num' => '۲', 'title' => 'بررسی نیاز', 'text' => 'تحلیل درخواست و مشخصات فنی شما.' ),
			array( 'num' => '۳', 'title' => 'یافتن تأمین‌کننده', 'text' => 'جستجوی منبع معتبر در شبکه بین‌المللی.' ),
			array( 'num' => '۴', 'title' => 'ارائه قیمت و شرایط', 'text' => 'اعلام قیمت، زمان و شرایط تحویل.' ),
			array( 'num' => '۵', 'title' => 'هماهنگی خرید و تجارت', 'text' => 'انجام خرید، قرارداد و مسیر حمل.' ),
		),

		'trade_form_enabled'         => '1',
		'trade_form_title'           => 'فرم درخواست تأمین کالا',
		'trade_form_intro'           => 'اطلاعات کالا و بازار هدف را بفرستید تا مسیر تأمین را برایتان روشن کنیم.',
		'trade_form_banner_title'    => 'تجارت بدون مرز از مسیر ایران و روسیه',
		'trade_form_banner_text'     => 'Global connections · Real opportunities',
		'trade_form_banner_image'    => 'hero-student.jpg',
		'trade_form_banner_image_id' => 0,
		'trade_form_name_label'      => 'نام و نام خانوادگی',
		'trade_form_name_ph'         => 'مثلاً سارا احمدی',
		'trade_form_phone_label'     => 'شماره تماس / واتساپ',
		'trade_form_phone_ph'        => '۰۹۱۲xxxxxxx',
		'trade_form_product_label'   => 'نام کالا',
		'trade_form_product_ph'      => 'مثلاً پسته فندقی',
		'trade_form_category_label'  => 'دسته‌بندی کالا',
		'trade_form_categories'      => array(
			array( 'label' => 'انتخاب کنید', 'value' => '' ),
			array( 'label' => 'خشکبار', 'value' => 'nuts' ),
			array( 'label' => 'خرما', 'value' => 'dates' ),
			array( 'label' => 'مواد غذایی', 'value' => 'food' ),
			array( 'label' => 'ادویه', 'value' => 'spice' ),
			array( 'label' => 'غلات', 'value' => 'grain' ),
			array( 'label' => 'آرایشی و بهداشتی', 'value' => 'cosmetics' ),
			array( 'label' => 'کالاهای روسی', 'value' => 'russian' ),
			array( 'label' => 'سایر', 'value' => 'other' ),
		),
		'trade_form_origin_label'    => 'کشور مبدأ خرید',
		'trade_form_origin_ph'       => 'ایران / روسیه / سایر',
		'trade_form_dest_label'      => 'کشور مقصد',
		'trade_form_dest_ph'         => 'مثلاً روسیه',
		'trade_form_qty_label'       => 'حجم یا تعداد موردنیاز',
		'trade_form_qty_ph'          => 'مثلاً ۱۰۰ کیلوگرم',
		'trade_form_specs_label'     => 'مشخصات فنی یا برند',
		'trade_form_specs_ph'        => 'مثلاً درجه یک، بسته‌بندی صادراتی',
		'trade_form_notes_label'     => 'توضیحات تکمیلی',
		'trade_form_notes_ph'        => 'جزئیات بیشتر درباره کیفیت، زمان یا مجوزها',
		'trade_form_file_label'      => 'آپلود عکس یا فایل محصول',
		'trade_form_file_note'       => 'فرمت مجاز: JPG، PNG، PDF — حداکثر ۱۰ مگابایت',
		'trade_form_submit'          => 'ارسال درخواست',
		'trade_form_note'            => 'اطلاعات فقط برای هماهنگی تأمین کالا استفاده می‌شود.',
		'trade_form_success'         => 'درخواست تأمین ثبت شد. مشاوران لایف روس به‌زودی با شما تماس می‌گیرند.',

		'trade_cats_enabled'    => '1',
		'trade_cats_title'      => 'دسته‌بندی محصولات',
		'trade_cats_subtitle'   => 'برخی از گروه‌هایی که لایف روس مسیر تأمین آن‌ها را همراهی می‌کند.',
		'trade_cats'            => array(
			array( 'title' => 'پسته و خشکبار', 'image' => 'universities/msu.jpg', 'image_id' => 0 ),
			array( 'title' => 'خرما', 'image' => 'universities/sechenov.jpg', 'image_id' => 0 ),
			array( 'title' => 'مواد غذایی', 'image' => 'universities/hse.jpg', 'image_id' => 0 ),
			array( 'title' => 'ادویه‌جات', 'image' => 'universities/rudn.jpg', 'image_id' => 0 ),
			array( 'title' => 'غلات', 'image' => 'universities/spbu.jpg', 'image_id' => 0 ),
			array( 'title' => 'محصولات آرایشی و بهداشتی', 'image' => 'universities/bauman.jpg', 'image_id' => 0 ),
			array( 'title' => 'کالاهای روسی', 'image' => 'st-basil.jpg', 'image_id' => 0 ),
		),
		'trade_cats_notice'     => 'اگر کالای موردنظر شما در این فهرست نیست، مشخصات را برای ما بفرستید تا امکان تأمین بررسی شود.',

		'trade_cta_enabled'     => '1',
		'trade_cta_title'       => 'آماده شروع تجارت هستید؟',
		'trade_cta_text'        => 'از سورسینگ تا قرارداد و مسیر حمل، یک تیم پاسخگو کنار شماست.',
		'trade_cta1_text'       => 'درخواست تأمین کالا',
		'trade_cta1_link'       => '#consultation',
		'trade_cta2_text'       => 'مشاوره با بخش بازرگانی لایف روس',
		'trade_cta2_link'       => '/contact/',
		'trade_seo_title'       => 'تجارت و تأمین کالا ایران و روسیه | لایف روس',
		'trade_seo_description' => 'سورسینگ، خرید از روسیه و صادرات محصولات ایران با همراهی لایف روس.',
	);
}
